### ISSUE TITLE
String.iteri

### ISSUE THREAD

**Issue by fangyi-zhou** [janestreet/base#106]
Is there any particular reason that `iteri` is not in the String module?

**Comment by bcc32** [comment]
It's probably just an ommission.  `iteri` isn't part of the `Container.S0` interface, so it's specified explicitly in `Array` for example.

I'll go ahead and add `String.iteri`.

**Comment by fangyi-zhou** [comment]
It seems that it was part of `Indexed_Container`, maybe you can also other friends of `iteri` altogether

**Comment by bcc32** [comment]
Yep, that seems good.  We'll add `Indexed_container.S0` and make `String` implement that interface.

**Comment by aalekseyev** [comment]
The fix was pushed in 29aaaa285d2dadbde99a1051d13b8223e2f85e8b.

**Comment by fangyi-zhou** [comment]
Thanks!
