### ISSUE TITLE
Functional Array.rev? 

### ISSUE THREAD

**Issue by dieggsy** [janestreet/base#108]
I'm totally new to OCaml, but I think it's really neat that the `Array` module supports functional operations on arrays. One thing I sort of missed which I think can be quite useful is a functional reverse (in the style of `List.rev`), which I've simply defined below in terms of `Array.copy` and `Array.rev_inplace`.

```ocaml
  let array_rev array =
    let copy = Array.copy array in
    Array.rev_inplace copy;
    copy
```
Is there good reason something like this shouldn't be in the `Array` module?

**Comment by seliopou** [comment]
Sure, we can add that.

**Comment by aalekseyev** [comment]
Added in 74e7608

**Comment by seliopou** [comment]
Closing, as the change has been merged.
