### ISSUE TITLE
Option.value where default is lazy?

### ISSUE THREAD

**Issue by brendanlong** [janestreet/base#109]
It comes up fairly often that we want to do something like `Option.value` but have the `~default` argument evaluated lazily. For example, we might read configs from environment variables if they're not provided:

```ocaml
let default_x () =
  lazy (
    match Sys.getenv "x" with
    | Some x -> x
    | None -> assert false)

let do_thing ?x () =
  let x = Option.value ~default:(Lazy.force x) in
  ...
```

The problem is that the `Lazy.force x` gets evaluated whether or not we already have a value for `x`.

In our code we have a bunch of:

```ocaml
let do_thing ?x () =
  let x =
    match x with
    | Some x -> x
    | None -> Lazy.force default_x
  in
  ...
```

But that's annoying, and it's a problem when the right way of doing something (the big match statement) is harder than the wrong way (using `Option.value`).

I just added a helper in our code:

```ocaml
(* option.ml *)
let value_lazy_default t ~default =
  match t with
  | Some value -> value
  | None -> Lazy.force default
;;
```

But I'm curious if you'd be open to adding this to Base?

**Comment by dwang20151005** [comment]
I have wanted this too!

**Comment by brendanlong** [comment]
Just realized I already made a PR for this a while back #93

**Comment by bcc32** [comment]
Closing as a duplicate, please see #93.
