### ISSUE TITLE
Links to changes from API documentation does not exist (404)

### ISSUE THREAD

**Issue by tcoopman** [janestreet/base#110]
https://ocaml.janestreet.com/ocaml-core/latest/doc/base/index.html links to https://ocaml.janestreet.com/ocaml-core/latest/doc/base/_doc-dir/CHANGES.md but that does not exist -> 404 Not Found

**Comment by bcc32** [comment]
This bug appears to affect our other libraries as well (I checked async and core).  @aalekseyev @cwong-ocaml might know more about our open-source publishing process.

**Comment by aalekseyev** [comment]
We're both new to this process and I can confirm the links are broken. 
I don't think I'm confident enough to mess with things to try to update 0.14, but we'll try to figure this out for when we're going to publish the next version. (unfortunately, not very soon)
