### ISSUE TITLE
documentation string for String.index/rindex seems misplaced

### ISSUE THREAD

**Issue by eriklovlie** [janestreet/base#112]
https://github.com/janestreet/base/blob/221b085f3fcd77597f8245b4d73de3970b238e71/src/string.mli#L70

Not clear to me why the documentation string appears in that place, since it seems to document the functions String.index and rindex that are a bit further down afaict.

**Comment by bcc32** [comment]
Yep, that's definitely wrong and has been for some time.  Looks like we accidentally split up the documentation from the functions when we moved `Caseless` to that location.  We'll fix this.

**Comment by aalekseyev** [comment]
This was fixed in d5c241f.

**Comment by bcc32** [comment]
Thanks for bringing this to our attention!
