### ISSUE TITLE
Error: Unbound module Sexplib0.Sexp_grammar

### ISSUE THREAD

**Issue by idkjs** [janestreet/base#114]
Hi. I tried to build this from source and got the falling error building with `4.12.0`
```sh
~/G/base (master)> dune build
File "src/sexplib.ml", line 9, characters 22-43:
9 | module Sexp_grammar = Sexplib0.Sexp_grammar
                          ^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module Sexplib0.Sexp_grammar
```

Looks like dune is install version 14.0 when it needs the master branch of `sexlib0`. `Sexp_grammar` does, in fact, not exist on version `14`'s [sexplib0.ml](https://github.com/janestreet/sexplib0/blob/v0.14/src/sexplib0.ml)

https://github.com/janestreet/sexplib0/blob/d29026829f320fcf7903f3828428ec921b04edc3/src/sexplib0.ml#L1-L9

Just an fyi. Please close if no action is required. Thank you.

**Comment by bcc32** [comment]
Have you added the [janestreet-bleeding](https://github.com/janestreet/opam-repository) repo to opam?  That will allow opam to use the unreleased versions of Jane Street packages, so opam doesn't try to mix and match incompatible versions of the packages.

I believe this error would be expected if you tried to build the tip of this repo against `0.14` of `sexplib0`.

**Comment by idkjs** [comment]
Thank you, @bcc32. Will try `bleeding`.
