### ISSUE TITLE
What is the policy regarding support for older OCaml versions ?

### ISSUE THREAD

**Issue by hhugo** [janestreet/base#149]
> Base will maintain compatibility with the latest OCaml release, and the three
prior minor version releases.

The above was recently dropped from the Readme. What should now one expect in term of compatibility ?

**Comment by hhugo** [comment]
It also seems that 32bit support was dropped ...

**Comment by dkalinichenko-js** [comment]
Hi! We'll make an announcement with the full v0.16 release, which should happen very soon, hopefully this week.
