### ISSUE TITLE
Base does not compile under ARMv7

### ISSUE THREAD

**Issue by darioteixeira** [janestreet/base#15]
I got the following compilation error when attempting to install Base via OPAM on a Raspberry Pi 3 running Stretch (with gcc 6.3.0):

```
/home/pi/.opam/ocaml-base-compiler.4.04.0/bin/ocamlc.opt -g -ccopt -g -ccopt -D_LARGEFILE64_SOURCE -ccopt -mpopcnt -o am_testing.o am_testing.c
gcc: error: unrecognized command line option ‘-mpopcnt’
```

I suspect `-mpopcnt` may be x86 specific.

**Comment by burnoutberni** [comment]
Same here on a Raspberry Pi 3 on jessie.

```
#=== ERROR while installing base.v0.9.114.41+37 ===============================#
# opam-version 1.2.2
# os           linux
# command      jbuilder build --only-packages base --root . -j 4 @install
# path         /home/pi/.opam/4.04.0/build/base.v0.9.114.41+37
# compiler     4.04.0
# exit-code    1
# env-file     /home/pi/.opam/4.04.0/build/base.v0.9.114.41+37/base-3259-487456.env
# stdout-file  /home/pi/.opam/4.04.0/build/base.v0.9.114.41+37/base-3259-487456.out
# stderr-file  /home/pi/.opam/4.04.0/build/base.v0.9.114.41+37/base-3259-487456.err
### stderr ###
#     ocamllex src/hex_lexer.ml
#       ocamlc src/am_testing.o (exit 2)
# (cd _build/default/src && /home/pi/.opam/4.04.0/bin/ocamlc.opt -g -ccopt -g -ccopt -D_LARGEFILE64_SOURCE -ccopt -mpopcnt -o am_testing.o am_testing.c)
# gcc: error: unrecognized command line option ‘-mpopcnt’
```

**Comment by diml** [comment]
I pushed a fix internally, it'll be availabe soon. This is the fix:

- replace `-mpopcnt` by `(:include mpopcnt.sexp)`
- add:

```scheme
(rule
 ((targets (mpopcnt.sexp))
  (action
   (progn
    (create_file empty.c)
    (system "${CC} -mpopcnt -c empty.c 2> ${null} && \
echo '(-mpopcnt)' > ${@} || echo '()' > ${@}")))))
```

**Comment by malbado** [comment]
I removed '-mpopcnt' from src/jbuild. When I use only 'make', everything deems Okay. However when I use opam install base the same error comes back again. It seems opam download the code again and erase my updates. 

In the following the output when I remove '-mpopcnt' and only use 'make'.
`jbuilder build @install
    ocamllex src/hex_lexer.ml
       ocaml src/int63_backend.ml
       ocaml src/string_set_primitives.ml
      ocamlc src/am_testing.o
      ocamlc src/exn_stubs.o
      ocamlc src/heap_block_stubs.o
      ocamlc src/hash_stubs.o
      ocamlc src/int_math_stubs.o
      ocamlc src/base__.{cmi,cmo,cmt}
    ocamldep compiler-stdlib/gen/gen.depends.ocamldep-output
    ocamldep shadow-stdlib/src/shadow_stdlib.depends.ocamldep-output
    ocamllex shadow-stdlib/gen/mapper.ml
    ocamldep src/base.dependsi.ocamldep-output
    ocamldep src/base.depends.ocamldep-output
      ocamlc compiler-stdlib/gen/gen.{cmi,cmo,cmt}
    ocamldep shadow-stdlib/gen/gen.depends.ocamldep-output
      ocamlc src/internalhash_stubs.o
      ocamlc src/string_dict_stubs.o
    ocamlopt src/base__.{cmx,o}
    ocamlopt compiler-stdlib/gen/gen.{cmx,o}
  ocamlmklib src/dllbase_stubs.so,src/libbase_stubs.a
    ocamlopt compiler-stdlib/gen/gen.exe
         gen compiler-stdlib/src/caml.ml
    ocamldep compiler-stdlib/src/caml.depends.ocamldep-output
      ocamlc compiler-stdlib/src/caml.{cmi,cmo,cmt}
      ocamlc compiler-stdlib/src/caml.cma
      ocamlc shadow-stdlib/gen/mapper.{cmi,cmo,cmt}
      ocamlc shadow-stdlib/gen/gen.{cmi,cmo,cmt}
    ocamlopt compiler-stdlib/src/caml.{cmx,o}
    ocamlopt compiler-stdlib/src/caml.{a,cmxa}
    ocamlopt shadow-stdlib/gen/mapper.{cmx,o}
    ocamlopt compiler-stdlib/src/caml.cmxs
    ocamlopt shadow-stdlib/gen/gen.{cmx,o}
    ocamlopt shadow-stdlib/gen/gen.exe
         gen shadow-stdlib/src/shadow_stdlib.mli
    ocamldep shadow-stdlib/src/shadow_stdlib.dependsi.ocamldep-output
      ocamlc shadow-stdlib/src/shadow_stdlib.{cmi,cmti}
      ocamlc src/base__Field.{cmi,cmti}
      ocamlc src/base__Ppx_compare_lib.{cmi,cmti}
      ocamlc shadow-stdlib/src/shadow_stdlib.{cmo,cmt}
      ocamlc src/base__Sys.{cmi,cmti}
      ocamlc src/base__Variant.{cmi,cmti}
      ocamlc src/base__Hex_lexer.{cmi,cmo,cmt}
      ocamlc src/base__String_set_primitives.{cmi,cmo,cmt}
      ocamlc src/base__Field.{cmo,cmt}
      ocamlc shadow-stdlib/src/shadow_stdlib.cma
      ocamlc src/base__Fieldslib.{cmi,cmo,cmt}
      ocamlc src/base__Variant.{cmo,cmt}
      ocamlc src/base__Variantslib.{cmi,cmo,cmt}
    ocamlopt shadow-stdlib/src/shadow_stdlib.{cmx,o}
    ocamlopt shadow-stdlib/src/shadow_stdlib.{a,cmxa}
    ocamlopt src/base__Field.{cmx,o}
    ocamlopt src/base__Hex_lexer.{cmx,o}
    ocamlopt src/base__String_set_primitives.{cmx,o}
    ocamlopt src/base__Variant.{cmx,o}
    ocamlopt src/base__Fieldslib.{cmx,o}
    ocamlopt shadow-stdlib/src/shadow_stdlib.cmxs
      ocamlc src/base__Import0.{cmi,cmo,cmt}
      ocamlc src/base__Polymorphic_compare.{cmi,cmti}
      ocamlc src/base__Printf.{cmi,cmti}
      ocamlc src/base__Hash_intf.{cmi,cmo,cmt}
      ocamlc src/base__Linked_queue0.{cmi,cmo,cmt}
      ocamlc src/base__List0.{cmi,cmo,cmt}
      ocamlc src/base__Sys0.{cmi,cmo,cmt}
      ocamlc src/base__Uchar0.{cmi,cmo,cmt}
      ocamlc src/base__Polymorphic_compare.{cmo,cmt}
      ocamlc src/base__Poly.{cmi,cmo,cmt}
      ocamlc src/base__Printf.{cmo,cmt}
      ocamlc src/base__Hash.{cmi,cmti}
    ocamlopt src/base__Variantslib.{cmx,o}
      ocamlc src/base__Array0.{cmi,cmo,cmt}
      ocamlc src/base__String0.{cmi,cmo,cmt}
      ocamlc src/base__Char0.{cmi,cmo,cmt}
      ocamlc src/base__Ppx_hash_lib.{cmi,cmo,cmt}
      ocamlc src/base__Ppx_compare_lib.{cmo,cmt}
      ocamlc src/base__Sexp.{cmi,cmti}
      ocamlc src/base__Import.{cmi,cmo,cmt}
      ocamlc src/base__Hash.{cmo,cmt}
      ocamlc src/base__Sexplib.{cmi,cmo,cmt}
      ocamlc src/base__Sexp.{cmo,cmt}
      ocamlc src/base__Avltree.{cmi,cmti}
      ocamlc src/base__Binary_search.{cmi,cmti}
      ocamlc src/base__String_dict.{cmi,cmti}
      ocamlc src/base__Fn.{cmi,cmti}
      ocamlc src/base__Int_pow2.{cmi,cmti}
      ocamlc src/base__Popcount.{cmi,cmti}
      ocamlc src/base__Random.{cmi,cmti}
      ocamlc src/base__Staged.{cmi,cmti}
      ocamlc src/base__Pretty_printer.{cmi,cmti}
      ocamlc src/base__With_return.{cmi,cmti}
      ocamlc src/base__Binary_searchable_intf.{cmi,cmo,cmt}
      ocamlc src/base__Applicative_intf.{cmi,cmo,cmt}
      ocamlc src/base__Blit_intf.{cmi,cmo,cmt}
      ocamlc src/base__Equal.{cmi,cmo,cmt}
      ocamlc src/base__Floatable.{cmi,cmo,cmt}
      ocamlc src/base__Hasher.{cmi,cmo,cmt}
      ocamlc src/base__Intable.{cmi,cmo,cmt}
      ocamlc src/base__Polymorphic_compare_intf.{cmi,cmo,cmt}
      ocamlc src/base__Stringable.{cmi,cmo,cmt}
      ocamlc src/base__T.{cmi,cmo,cmt}
      ocamlc src/base__Sys.{cmo,cmt}
      ocamlc src/base__Backtrace.{cmi,cmti}
      ocamlc src/base__Comparator.{cmi,cmti}
      ocamlc src/base__Heap_block.{cmi,cmti}
      ocamlc src/base__Maybe_bound.{cmi,cmti}
      ocamlc src/base__Word_size.{cmi,cmti}
      ocamlc src/base__Monad_intf.{cmi,cmo,cmt}
      ocamlc src/base__Commutative_group.{cmi,cmo,cmt}
      ocamlc src/base__Sign0.{cmi,cmo,cmt}
      ocamlc src/base__Fn.{cmo,cmt}
      ocamlc src/base__String_dict.{cmo,cmt}
      ocamlc src/base__Popcount.{cmo,cmt}
      ocamlc src/base__Avltree.{cmo,cmt}
      ocamlc src/base__Staged.{cmo,cmt}
      ocamlc src/base__Array_permute.{cmi,cmo,cmt}
      ocamlc src/base__Exn.{cmi,cmti}
      ocamlc src/base__Binary_searchable.{cmi,cmti}
      ocamlc src/base__Pretty_printer.{cmo,cmt}
      ocamlc src/base__Blit.{cmi,cmti}
      ocamlc src/base__Ordering.{cmi,cmti}
      ocamlc src/base__Sexpable.{cmi,cmti}
      ocamlc src/base__Comparator.{cmo,cmt}
      ocamlc src/base__Word_size.{cmo,cmt}
      ocamlc src/base__Heap_block.{cmo,cmt}
      ocamlc src/base__Source_code_position0.{cmi,cmo,cmt}
      ocamlc src/base__Random.{cmo,cmt}
      ocamlc src/base__Monad.{cmi,cmti}
      ocamlc src/base__Binary_searchable.{cmo,cmt}
      ocamlc src/base__With_return.{cmo,cmt}
      ocamlc src/base__Exn.{cmo,cmt}
      ocamlc src/base__Ordering.{cmo,cmt}
      ocamlc src/base__Buffer_intf.{cmi,cmo,cmt}
      ocamlc src/base__Sexpable.{cmo,cmt}
      ocamlc src/base__Invariant_intf.{cmi,cmo,cmt}
    ocamlopt src/base__Import0.{cmx,o}
      ocamlc src/base__Applicative.{cmi,cmti}
      ocamlc src/base__Lazy.{cmi,cmti}
      ocamlc src/base__Monad.{cmo,cmt}
      ocamlc src/base__Invariant.{cmi,cmti}
      ocamlc src/base__Buffer.{cmi,cmti}
      ocamlc src/base__Result.{cmi,cmti}
    ocamlopt src/base__Hash_intf.{cmx,o}
    ocamlopt src/base__Linked_queue0.{cmx,o}
    ocamlopt src/base__List0.{cmx,o}
    ocamlopt src/base__Sys0.{cmx,o}
    ocamlopt src/base__Printf.{cmx,o}
    ocamlopt src/base__Polymorphic_compare.{cmx,o}
    ocamlopt src/base__Uchar0.{cmx,o}
      ocamlc src/base__Ordered_collection_common.{cmi,cmti}
      ocamlc src/base__Lazy.{cmo,cmt}
      ocamlc src/base__Info_intf.{cmi,cmo,cmt}
      ocamlc src/base__Result.{cmo,cmt}
      ocamlc src/base__Container_intf.{cmi,cmo,cmt}
    ocamlopt src/base__Poly.{cmx,o}
    ocamlopt src/base__String0.{cmx,o}
    ocamlopt src/base__Array0.{cmx,o}
      ocamlc src/base__Ordered_collection_common.{cmo,cmt}
      ocamlc src/base__Binary_search.{cmo,cmt}
      ocamlc src/base__Info.{cmi,cmti}
      ocamlc src/base__Blit.{cmo,cmt}
      ocamlc src/base__Container.{cmi,cmti}
      ocamlc src/base__Error.{cmi,cmti}
    ocamlopt src/base__Char0.{cmx,o}
    ocamlopt src/base__Ppx_compare_lib.{cmx,o}
      ocamlc src/base__Ref.{cmi,cmti}
      ocamlc src/base__Container.{cmo,cmt}
      ocamlc src/base__Sequence.{cmi,cmti}
      ocamlc src/base__List.{cmi,cmti}
      ocamlc src/base__Either_intf.{cmi,cmo,cmt}
      ocamlc src/base__Error.{cmo,cmt}
      ocamlc src/base__Indexed_container_intf.{cmi,cmo,cmt}
      ocamlc src/base__Int_pow2.{cmo,cmt}
      ocamlc src/base__Invariant.{cmo,cmt}
      ocamlc src/base__Or_error.{cmi,cmti}
      ocamlc src/base__Ref.{cmo,cmt}
      ocamlc src/base__Array.{cmi,cmti}
    ocamlopt src/base__Hash.{cmx,o}
      ocamlc src/base__Maybe_bound.{cmo,cmt}
      ocamlc src/base__Applicative.{cmo,cmt}
      ocamlc src/base__Info.{cmo,cmt}
      ocamlc src/base__Either.{cmi,cmti}
      ocamlc src/base__Indexed_container.{cmi,cmti}
      ocamlc src/base__List.{cmo,cmt}
    ocamlopt src/base__Ppx_hash_lib.{cmx,o}
      ocamlc src/base__Validate.{cmi,cmti}
      ocamlc src/base__Indexed_container.{cmo,cmt}
      ocamlc src/base__Or_error.{cmo,cmt}
      ocamlc src/base__Queue_intf.{cmi,cmo,cmt}
    ocamlopt src/base__Sexp.{cmx,o}
      ocamlc src/base__Sequence.{cmo,cmt}
    ocamlopt src/base__Import.{cmx,o}
      ocamlc src/base__Comparable_intf.{cmi,cmo,cmt}
      ocamlc src/base__Option.{cmi,cmti}
      ocamlc src/base__Validate.{cmo,cmt}
    ocamlopt src/base__Sexplib.{cmx,o}
      ocamlc src/base__Linked_queue.{cmi,cmti}
    ocamlopt src/base__Applicative_intf.{cmx,o}
    ocamlopt src/base__String_dict.{cmx,o}
      ocamlc src/base__Hashtbl_intf.{cmi,cmo,cmt}
    ocamlopt src/base__Binary_searchable_intf.{cmx,o}
    ocamlopt src/base__Blit_intf.{cmx,o}
    ocamlopt src/base__Equal.{cmx,o}
    ocamlopt src/base__Avltree.{cmx,o}
    ocamlopt src/base__Floatable.{cmx,o}
    ocamlopt src/base__Fn.{cmx,o}
      ocamlc src/base__Map_intf.{cmi,cmo,cmt}
    ocamlopt src/base__Hasher.{cmx,o}
    ocamlopt src/base__Intable.{cmx,o}
    ocamlopt src/base__Polymorphic_compare_intf.{cmx,o}
    ocamlopt src/base__Stringable.{cmx,o}
    ocamlopt src/base__Popcount.{cmx,o}
    ocamlopt src/base__Pretty_printer.{cmx,o}
    ocamlopt src/base__T.{cmx,o}
    ocamlopt src/base__Monad_intf.{cmx,o}
    ocamlopt src/base__Sys.{cmx,o}
      ocamlc src/base__Comparable.{cmi,cmti}
      ocamlc src/base__Float0.{cmi,cmo,cmt}
      ocamlc src/base__Option.{cmo,cmt}
    ocamlopt src/base__Commutative_group.{cmx,o}
    ocamlopt src/base__Comparator.{cmx,o}
      ocamlc src/base__Either.{cmo,cmt}
    ocamlopt src/base__Ordering.{cmx,o}
    ocamlopt src/base__Sign0.{cmx,o}
    ocamlopt src/base__Word_size.{cmx,o}
    ocamlopt src/base__Staged.{cmx,o}
      ocamlc src/base__Array.{cmo,cmt}
      ocamlc src/base__Hashtbl.{cmi,cmti}
      ocamlc src/base__Linked_queue.{cmo,cmt}
    ocamlopt src/base__Sexpable.{cmx,o}
      ocamlc src/base__Map.{cmi,cmti}
      ocamlc src/base__Comparable.{cmo,cmt}
      ocamlc src/base__Set_intf.{cmi,cmo,cmt}
      ocamlc src/base__Sexp_with_comparable.{cmi,cmti}
      ocamlc src/base__Source_code_position.{cmi,cmti}
      ocamlc src/base__Uchar.{cmi,cmti}
      ocamlc src/base__Bool.{cmi,cmti}
      ocamlc src/base__Identifiable.{cmi,cmti}
      ocamlc src/base__Type_equal.{cmi,cmti}
    ocamlopt src/base__Exn.{cmx,o}
    ocamlopt src/base__Heap_block.{cmx,o}
    ocamlopt src/base__Source_code_position0.{cmx,o}
    ocamlopt src/base__Monad.{cmx,o}
      ocamlc src/base__Hash_set_intf.{cmi,cmo,cmt}
    ocamlopt src/base__Random.{cmx,o}
      ocamlc src/base__Sexp_with_comparable.{cmo,cmt}
      ocamlc src/base__Set.{cmi,cmti}
      ocamlc src/base__Identifiable.{cmo,cmt}
      ocamlc src/base__Bool.{cmo,cmt}
      ocamlc src/base__Uchar.{cmo,cmt}
      ocamlc src/base__Char.{cmi,cmti}
      ocamlc src/base__Sign.{cmi,cmti}
      ocamlc src/base__Unit.{cmi,cmti}
      ocamlc src/base__Int_intf.{cmi,cmo,cmt}
      ocamlc src/base__String.{cmi,cmti}
      ocamlc src/base__Map.{cmo,cmt}
    ocamlopt src/base__Invariant_intf.{cmx,o}
    ocamlopt src/base__With_return.{cmx,o}
    ocamlopt src/base__Lazy.{cmx,o}
    ocamlopt src/base__Result.{cmx,o}
    ocamlopt src/base__Array_permute.{cmx,o}
      ocamlc src/base__Hash_set.{cmi,cmti}
      ocamlc src/base__Sign.{cmo,cmt}
      ocamlc src/base__Char.{cmo,cmt}
      ocamlc src/base__Unit.{cmo,cmt}
      ocamlc src/base__Int.{cmi,cmti}
      ocamlc src/base__Int32.{cmi,cmti}
      ocamlc src/base__Int63_emul.{cmi,cmti}
      ocamlc src/base__Int64.{cmi,cmti}
      ocamlc src/base__Nativeint.{cmi,cmti}
      ocamlc src/base__Int_conversions.{cmi,cmti}
      ocamlc src/base__Int_math.{cmi,cmti}
      ocamlc src/base__Buffer.{cmo,cmt}
    ocamlopt src/base__Info_intf.{cmx,o}
    ocamlopt src/base__Ordered_collection_common.{cmx,o}
    ocamlopt src/base__Container_intf.{cmx,o}
      ocamlc src/base__Set.{cmo,cmt}
      ocamlc src/base__Type_equal.{cmo,cmt}
      ocamlc src/base__Hash_set.{cmo,cmt}
      ocamlc src/base__Source_code_position.{cmo,cmt}
      ocamlc src/base__String.{cmo,cmt}
      ocamlc src/base__Backtrace.{cmo,cmt}
      ocamlc src/base__Int63_backends.{cmi,cmo,cmt}
      ocamlc src/base__Pow_overflow_bounds.{cmi,cmo,cmt}
      ocamlc src/base__Int_conversions.{cmo,cmt}
      ocamlc src/base__Hashtbl.{cmo,cmt}
      ocamlc src/base__Int32.{cmo,cmt}
      ocamlc src/base__Int64.{cmo,cmt}
      ocamlc src/base__Nativeint.{cmo,cmt}
      ocamlc src/base__Int.{cmo,cmt}
    ocamlopt src/base__Binary_search.{cmx,o}
    ocamlopt src/base__Blit.{cmx,o}
      ocamlc src/base__Int63_emul.{cmo,cmt}
      ocamlc src/base__Int63_backend.{cmi,cmo,cmt}
    ocamlopt src/base__Ref.{cmx,o}
    ocamlopt src/base__Binary_searchable.{cmx,o}
    ocamlopt src/base__Buffer_intf.{cmx,o}
      ocamlc src/base__Int_math.{cmo,cmt}
    ocamlopt src/base__Container.{cmx,o}
      ocamlc src/base__Int63.{cmi,cmti}
    ocamlopt src/base__Indexed_container_intf.{cmx,o}
      ocamlc src/base__Float.{cmi,cmti}
      ocamlc src/base__Int63.{cmo,cmt}
    ocamlopt src/base__Indexed_container.{cmx,o}
    ocamlopt src/base__Queue_intf.{cmx,o}
      ocamlc src/base__Float.{cmo,cmt}
    ocamlopt src/base__List.{cmx,o}
    ocamlopt src/base__Maybe_bound.{cmx,o}
    ocamlopt src/base__Applicative.{cmx,o}
    ocamlopt src/base__Info.{cmx,o}
    ocamlopt src/base__Error.{cmx,o}
    ocamlopt src/base__Int_pow2.{cmx,o}
    ocamlopt src/base__Invariant.{cmx,o}
    ocamlopt src/base__Either_intf.{cmx,o}
    ocamlopt src/base__Or_error.{cmx,o}
    ocamlopt src/base__Sequence.{cmx,o}
    ocamlopt src/base__Validate.{cmx,o}
    ocamlopt src/base__Comparable_intf.{cmx,o}
    ocamlopt src/base__Option.{cmx,o}
    ocamlopt src/base__Hashtbl_intf.{cmx,o}
      ocamlc src/base.{cmi,cmo,cmt}
    ocamlopt src/base__Float0.{cmx,o}
    ocamlopt src/base__Map_intf.{cmx,o}
      ocamlc src/base.cma
    ocamlopt src/base__Comparable.{cmx,o}
    ocamlopt src/base__Identifiable.{cmx,o}
    ocamlopt src/base__Sexp_with_comparable.{cmx,o}
    ocamlopt src/base__Either.{cmx,o}
    ocamlopt src/base__Unit.{cmx,o}
    ocamlopt src/base__Uchar.{cmx,o}
    ocamlopt src/base__Sign.{cmx,o}
    ocamlopt src/base__Bool.{cmx,o}
    ocamlopt src/base__Int_intf.{cmx,o}
    ocamlopt src/base__Set_intf.{cmx,o}
    ocamlopt src/base__Array.{cmx,o}
    ocamlopt src/base__Linked_queue.{cmx,o}
    ocamlopt src/base__Map.{cmx,o}
    ocamlopt src/base__Set.{cmx,o}
    ocamlopt src/base__Char.{cmx,o}
    ocamlopt src/base__String.{cmx,o}
    ocamlopt src/base__Buffer.{cmx,o}
    ocamlopt src/base__Int_conversions.{cmx,o}
    ocamlopt src/base__Pow_overflow_bounds.{cmx,o}
    ocamlopt src/base__Int_math.{cmx,o}
    ocamlopt src/base__Int32.{cmx,o}
    ocamlopt src/base__Nativeint.{cmx,o}
    ocamlopt src/base__Int64.{cmx,o}
    ocamlopt src/base__Int.{cmx,o}
    ocamlopt src/base__Source_code_position.{cmx,o}
    ocamlopt src/base__Int63_emul.{cmx,o}
    ocamlopt src/base__Type_equal.{cmx,o}
    ocamlopt src/base__Hashtbl.{cmx,o}
    ocamlopt src/base__Backtrace.{cmx,o}
    ocamlopt src/base__Hash_set_intf.{cmx,o}
    ocamlopt src/base__Int63_backends.{cmx,o}
    ocamlopt src/base__Int63_backend.{cmx,o}
    ocamlopt src/base__Int63.{cmx,o}
    ocamlopt src/base__Hash_set.{cmx,o}
    ocamlopt src/base__Float.{cmx,o}
    ocamlopt src/base.{cmx,o}
    ocamlopt src/base.{a,cmxa}
    ocamlopt src/base.cmxs
`
And in the following the output when I used opam install base
`#=== ERROR while installing base.v0.9.2 =======================================#
# opam-version 1.2.0
# os           linux
# command      jbuilder build -p base -j 1
# path         /home/pi/.opam/4.04.0/build/base.v0.9.2
# compiler     4.04.0
# exit-code    1
# env-file     /home/pi/.opam/4.04.0/build/base.v0.9.2/base-12719-6d07ae.env
# stdout-file  /home/pi/.opam/4.04.0/build/base.v0.9.2/base-12719-6d07ae.out
# stderr-file  /home/pi/.opam/4.04.0/build/base.v0.9.2/base-12719-6d07ae.err
### stderr ###
#     ocamllex src/hex_lexer.ml
#        ocaml src/int63_backend.ml
#        ocaml src/string_set_primitives.ml
#       ocamlc src/am_testing.o (exit 2)
# (cd _build/default/src && /home/pi/.opam/4.04.0/bin/ocamlc.opt -g -I /home/pi/.opam/4.04.0/lib/sexplib/0 -I ../compiler-stdlib/src -I ../shadow-stdlib/src -ccopt -g -ccopt -D_LARGEFILE64_SOURCE -ccopt -mpopcnt -o am_testing.o am_testing.c)
# gcc: error: unrecognized command line option ‘-mpopcnt’
`

**Comment by diml** [comment]
Do you get the error with the master branch?

**Comment by xguerin** [comment]
I just ran into that problem today: `popcntq`, generated by `-mpopcnt`, is not supported by OpenBSD's version of `gas` (some clues here: http://openbsd-archive.7691.n7.nabble.com/GCC-OpenMP-march-td292517.html#a292576). Any chance `popcntq` check can be added at the assembler level as well ?

**Comment by diml** [comment]
I think we should just move this function to core_kernel

**Comment by mato** [comment]
Any progress on cutting a release with the fix? I get the same error on `opam install base` (via a dependency of `mirage`). Host is an `aarch64` box running Ubuntu 16.04.2 LTS.

Installing via an `opam pin` of `master` works but requires updating my switch to `4.04.1`.

**Comment by diml** [comment]
Sure, we can do a new release.

@xguerin, IIUC the C compiler accepts -mpopcnt but then  the assembler complains? Can you try changing the check to `${CC} -mpopcnt -o empty.exe empty.c` to see if it's enough?

**Comment by xguerin** [comment]
Correct. I just checked, that's not enough. A `popctnq` instruction needs to be emitted for the assembler to complain. I can reproduce the problem with the following:

```c
int main (int argc, char ** argv) {
  return __builtin_popcountll ((long long) argv);
}
```

**Comment by diml** [comment]
Thanks, I'll merge #17 and do a release

**Comment by diml** [comment]
https://github.com/ocaml/opam-repository/pull/9517

**Comment by xguerin** [comment]
thanks !

**Comment by argent-smith** [comment]
> I think we should just move this function to core_kernel
@diml now core_kernel does’t compile on armv7 with this very error.
