### ISSUE TITLE
No docs

### ISSUE THREAD

**Issue by LAC-Tech** [janestreet/base#159]
I go here:

https://opensource.janestreet.com/base/

There's a link to API Docs, which takes me here

https://ocaml.org/p/base/v0.15.0/doc/Base/index.html

And I get:

Page not found
We're sorry, for some reason we don't have the documentation for this package.

**Comment by tanelso2** [comment]
Also running in to this problem. Makes it difficult to use the library

**Comment by tanelso2** [comment]
Docs can be found here: https://ocaml.org/p/base/v0.16.3/doc/Base/List/index.html
