### ISSUE TITLE
List.findi_exn is missing

### ISSUE THREAD

**Issue by shepard8** [janestreet/base#19]
I  found myself writing

    let find_index v l =
      match List.findi l ~f:(fun _ c -> c = v) with
      | None -> raise Not_found
      | Some (i, _) -> i

instead of

    let find_index v l =
      List.findi_exn l ~f:(fun _ c -> c = v) |> fst

as there is no `findi_exn` function in the `List` module. As most functions here have a `_exn` variant, I see no reason why `findi` would not have its own?

**Comment by yminsky** [comment]
Note that you can also write:

``` ocaml
List.findi l ~f |> Option.value_exn |> fst
```
Which greatly reduces the pain of not having the _exn version.

**Comment by shepard8** [comment]
I agree, but as I am working with lists I expect a Not_found exception. However I have seen in the roadmap that you plan to replace the Not_found exceptions by more meaningful messages, so maybe I should not worry about that.

**Comment by yminsky** [comment]
Indeed, relying on Not_found being thrown is generally considered an anti-pattern.

**Comment by shepard8** [comment]
Oh, I wasn't aware of that. Then as you pointed out earlier there is no real need for a findi_exn. Feel free to close this issue. Sorry for the useless noise and thanks for the indications!

**Comment by yminsky** [comment]
Lovely. Closed.
