### ISSUE TITLE
Transparency?

### ISSUE THREAD

**Issue by bluddy** [janestreet/base#2]
I'm definitely willing to entertain the notion of switching to Base for the sake of unity around a common stdlib/build tool. We're wasting precious resources splitting our efforts and bridging over impedance mismatches.

Given your willingness to work on streamlining the requirements and reducing compilation time, are you also going to make development more transparent and be more open to the community, including the decision process concerning community contributions?

**Comment by yminsky** [comment]
The plan is for community contributions to be handled in a straightforward fashion: patches will be submitted as PRs on github, and discussed and evaluated there initially. I expect that PRs will be evaluated by the reviewers of Base, which is primarily Stephen Weeks, Jeremie Dimino, and Thomas Refis.

Also, contributors to Base, like the rest of our open source libraries, will need to sign our CLA:

https://blogs.janestreet.com/core-icla-1_2_1.pdf

Changes will also come from our internal development process, which is not going to be done on Github. That's hard to see changing in the near term, given how integrated Base is into our internal, monorepo-based, development system.
