### ISSUE TITLE
module types T, T1, and T2 are not exported 

### ISSUE THREAD

**Issue by ivg** [janestreet/base#21]
In previous versions of Core these module types were exported to the top level, so that we were able to use them as `T`, `T1`, etc after the `Core_kernel.Std` or `Core.Std` is opened.  Base introduces an extra layer of indirection, e.g., we now write `T.T`, `T.T1`, etc. Is it intended? It looks weird to me (very smlish) and also complicates the process of migration from core to base.

**Comment by seliopou** [comment]
This will be included in our next push to GitHub. Thanks!
