### ISSUE TITLE
The `@@` operator is not exported

### ISSUE THREAD

**Issue by ivg** [janestreet/base#22]
I'm not sure whether it is intentional or not (I hope not), but this operator is not exposed and any usage provokes a warning: 
```
There is not equivalent functionality in Base or Stdio at the moment,
so you need to use [Caml.( @@ )] instead
```

The `@@` operator is a part of OCaml language for quite a few time and hiding it may confuse new users and irritate experienced.

**Comment by ivg** [comment]
btw, probaby, the warning message should say "There is no" instead of "There is not".

**Comment by yminsky** [comment]
Agreed. This seems like an oversight. I'll see if I can patch it.

**Comment by ivg** [comment]
btw, can you send me your CLA (if you still use them). As many minor issues can be resolved directly with a PR instead of creating an issue. Like this for example.

**Comment by yminsky** [comment]
The CLA is now back up.

**Comment by seliopou** [comment]
Thanks for opening the issue! This will be in the next sync to GitHub.
