### ISSUE TITLE
usability issue with `Continue_or_stop` and `Finished_or_stopped`

### ISSUE THREAD

**Issue by ivg** [janestreet/base#23]
Data constructors defined in these modules are not re-exported anywhere (at least I didn't find it), so any usage requires full-qualification including the `Container_intf` module, e.g.,

```ocaml 
 match f acc a with
   | Container_intf.Continue_or_stop.Stop x -> Container_intf.Finished_or_stopped_early.Stopped_early x
```

First of all it is too verbose. Second the `Container_intf` as well as other `*_intf` modules are usually seen as internal modules in Core libraries, and it is the first time in my life, when I'm forced to reference them directly in the user code. Next, it is expected, that the `*_intf` module defines types and signatures, not data types. Finally, even without the this `Container_intf` name, an expression `Continue_or_stop.Stop` looks weird and still too verbose and doesn't contribute to the code understanding. Something like `Action.Step`, `Search.Stop`, `Traverse.Stopped_early`, or even just `Stop` or a polymorphic variant would be more readable. (Concerning the polymorphic variant, I don't see any reason for not using it here).

**Comment by yminsky** [comment]
Yeah, this is a little awkward, though with type-directed constructor disambiguation, you could imagine this working more cleanly. But I agree this is rather awkward in the API as it stands.

We tend to avoid polymorphic variants for this kind of use-case because the typing discipline is more error prone (for example, there are cases where typos can pass typechecking with polymorphic variants, but not with ordinary variants), and are generally slower.

That said, the present solution is clearly sub-optimal.

@seliopou, @trefis, what do you guys think?

**Comment by ivg** [comment]
Concerning the type-directed constructor disambiguation, yes it would be nicer (provided that we will remove the `Container_intf` part), we can do something like this:
```ocaml
match f acc a with
| (Stop : _ Continue_or_stop.t) -> ...
```

or

```ocaml
match (f acc a : _ Continue_or_stop.t) with
| Stop  -> ...
```

However, the main problem is that it will trigger a warning by default. Of course, it is a warning, but most of the OCaml developers do not disable it and adhere to the recommendation, thus this warning effectively renders the type-directed disambiguation useless :( (I never understood, why they introduced such a nice mechanism, and then disabled it with a warning). 


Regarding the polymorphic variants, I tend to agree with your preferences, but in some cases there are tradeoffs, and I believe that in this particular case using a polymorphic variant would be viable option. Especially, since Core is already using polymorphic variants in similar cases, e.g., `partion_map`, `Map.merge`, `Binary_search`, etc. So, this would be at least consistent with the existing API.

**Comment by lpw25** [comment]
> Of course, it is a warning, but most of the OCaml developers do not disable it and adhere to the recommendation, thus this warning effectively renders the type-directed disambiguation useless

The warning doesn't render disambiguation useless, it still allows you to disambiguate constructors with the same name, which was the original aim of the feature. However, as the originator of this warning I can safely say that it should not be enabled by default -- something I've been meaning to change for a while.

Core and Base are designed to be used with warning 40 disabled. There are quite a few interfaces designed with this in mind, and I don't think we want to change them. IIRC jbuilder disables warning 40 by default -- so as long as you use jbuilder you'll be fine :-).

Of course, these constructors should still be available without going through `Container_intf` -- that really is an oversight.

**Comment by lpw25** [comment]
Ok, finally got around to it: https://github.com/ocaml/ocaml/pull/1333

**Comment by yminsky** [comment]
I just minted a feature to make this module available as an alias within Base.

**Comment by seliopou** [comment]
Thanks for opening the issue! This will be in the next sync to GitHub.
