### ISSUE TITLE
Conflict caused by use of @deprecated for shadow-stdlib

### ISSUE THREAD

**Issue by jberdine** [janestreet/base#26]
Since MPR#7444, GPR#1138 (included in 4.06), the use of @deprecated by shadow-stdlib is inconvenient / results in warning 3 needing to be disabled. It used to be that one could write:
```
include module type of (
  Base :
    module type of Base
    with module Format = Caml.Format )
```
in order to allow access to the standard Format module (for which Base/Core do not provide a more approved variant). Now such constructs trigger warning 3.

Perhaps there is somewhere I have yet to find to attach a `[@warning "-3"]` attribute to silence them?

To my understanding, the use of @deprecated by the shadow-stdlib does not use the standard semantics of deprecated. In the cases where there are alternatives in Base/Core, the deprecated attribute makes sense, but in the other cases it is not so clear.

**Comment by yminsky** [comment]
Yeah, I've never been entirely satisfied by this use of deprecation. In some sense, the real behavior we want is to make it possible to not open Pervasives at all when using Base. I'm not sure that this is a good in-between place to be.

@seliopou @trefis @diml : what would you guys think of getting rid of this deprecation step entirely in Base? Hopefully by 4.07, we can get [this](https://github.com/ocaml/ocaml/pull/1010) to land, at which point compiling without Pervasives would be easy?

**Comment by hhugo** [comment]
The following seems to work
```
include module type of (
  Base :
    module type of Base
    with module Format = Base.Format [@warning "-3"] )
```
