### ISSUE TITLE
Documentation: no "__"

### ISSUE THREAD

**Issue by Chris00** [janestreet/base#29]
The documentation should not contain any double underscore (you are probably well away of it, this is just meant to track the issue in the open).

Example:

![screenshot-2017-11-11 array base base array](https://user-images.githubusercontent.com/1255665/32689961-abe4c754-c6ee-11e7-8e4f-c6399f01bdf4.png)

**Comment by yminsky** [comment]
This is a bug, but it's also fixed in the tip version. We hope to have a new stable release with all these fixes in the next few weeks.

![image](https://user-images.githubusercontent.com/715302/32690499-c0c22352-c6c5-11e7-95cf-9e71f990ccbb.png)
