### ISSUE TITLE
Documentation: no duplicate "type t"

### ISSUE THREAD

**Issue by Chris00** [janestreet/base#30]
When including a module with `type t := t`, the documentation (when unfolding) should maybe gray out (or hide in some way) the `type t` in the included module: it is distracting and does not bring any information.
![screenshot-2017-11-11 array base base array 1](https://user-images.githubusercontent.com/1255665/32690013-581705e6-c6ef-11e7-9d54-1b228a33d2d9.png)

I know it may be controversial because the `type t` is indeed part of the included module but I think this should be discussed.  Maybe one can provide a way to go to the module sig (new page) and put inline a foldable "Coming from module ..." where only values and new types are present (in case of `type t := u` a type renaming could take place so the documentation reads in terms of the module one is looking at).

**Comment by yminsky** [comment]
That actually seems like an uncontroversial point. Destructive substitution removes the type in question, so I would have thought the correct answer is to remove the type.

@lpw25 @trefis, this seems like an odoc question. Do you have a view on this?

**Comment by lpw25** [comment]
It's a known bug in odoc. There is a slight issue in the case where the type being removed has documentation that you might not want to lose. I had considered rendering an explicit `type t := ...` in that case -- but to be honest I'm not sure it is worth the effort.

**Comment by yminsky** [comment]
Yeah, I think just deleting that documentation isn't too bad.

**Comment by trefis** [comment]
I created https://github.com/ocaml-doc/odoc/issues/96 to track the issue.
