### ISSUE TITLE
Documentation: second level include are not visible

### ISSUE THREAD

**Issue by Chris00** [janestreet/base#31]
When an included interface includes a second level one, the latter is not visible enough when it is open.
![screenshot-2017-11-12 list base base list](https://user-images.githubusercontent.com/1255665/32697375-45a9a756-c78f-11e7-9d90-eabd517aa7d6.png)
Moving the second level brace to the right will also prevent the first level one to be thinner in front of a closed second level include.

**Comment by yminsky** [comment]
@lpw25 @trefis I wonder if this should be closed here and filed instead against odoc, with the same example from Base....

**Comment by Chris00** [comment]
Fine with me but I opened it here because IMHO it would be nice that this be fixed for the v1 release of Base as it will be part of the experience with the library.

**Comment by lpw25** [comment]
I don't want to move the brace to the right because that doesn't scale to arbitrary depths (that's why it is a brace rather than a line in the first place). However, I agree that it isn't visible enough at the moment, so the curve of the brace should be extended further rightwards. The issue with the closed includes should also be fixed by not having a brace when the include is closed.

**Comment by lpw25** [comment]
Also, it would be better to raise these issues [here](github.com/ocaml-doc/odoc/issues). I happen to follow both repos, but not all the developers of odoc do. The issues also don't really have anything to do with base, and I think it would be a bad idea to delay the release of base until they are fixed.

**Comment by yminsky** [comment]
I mostly agree, but I do think that doing a push to try to get some documentation fixes out in time for Base coming out could be worthwhile, depending on the amount of work involved. Anyway, @Chris00 , would you mind moving or copying the issue over to odoc?

**Comment by yminsky** [comment]
(And I'm closing this one now, since I agree it doesn't really belong here.)

**Comment by yminsky** [comment]
Closing, and please move to odoc. We'll think about scheduling this along with the next release for Base as a separate matter.
