### ISSUE TITLE
Map.add is a terrible idea

### ISSUE THREAD

**Issue by smolkaj** [janestreet/base#32]
In the light of recent events, I feel obliged to open an issue about `Map.add`. The current semantics is that it adds a new entry to the map and **silently overwrites existing entries**, should one for the same key already be present.

I would be curious to hear the rational behind this unsafe semantics (I suppose there are historical reasons?). But whatever the reasons may be, I don't think they justify a bad interface. 

I think that the Jane Street libraries in general do a great job of following the principle of least surprise (really, no surprise) and making things as explicit as possible, both by using self-explanatory names and by using the type system to great effect. This is a notable exception.
It can lead to subtle bugs that are very hard to locate, and in particular cannot be found by starring at the code because the code is not explicit about it! Ironically, the fact that the Jane Street libraries usually have such a great, explicit interfaces makes this semantics of `Map.add` even more dangerous.

Just for sake of comparison, here is the interface of `Hashtbl`:
```
val add : ('a, 'b) t ‑> key:'a key ‑> data:'b ‑> [ `Ok | `Duplicate ]
val add_or_error : ('a, 'b) t ‑> key:'a key ‑> data:'b ‑> unit Or_error.t
val add_exn : ('a, 'b) t ‑> key:'a key ‑> data:'b ‑> unit
``` 
This is a great interface! And I hope it doesn't take much convincing to believe that it is a bad idea to give such different semantics to `Map.add` and `Hastbl.add`.

I seem to remember that `Map.add` was actually deprecated in previous releases of the library in favor of `Map.set`, which is a much better name for a function with this semantics. This seems like the right move. I'm certain the current interface has wasted lots of peoples precious time. (I have strong empirical evidence to believe so....)

**Comment by yminsky** [comment]
This is a reasonable concern, but my tendency is to think it's just too much churn to change it at this point.

**Comment by yminsky** [comment]
After some more internal discussion, folks decided that I was wrong, and that the churn was worth it, especially as we try to settle on a good and stable set of APIs for Base going forward. 

So you should expect this change to come to Base relatively soon.

**Comment by smolkaj** [comment]
Sweet, really happy to hear that! 👍

**Comment by neojski** [comment]
I think it just happened in this commit: https://github.com/janestreet/base/commit/57240d0d8403031f37e105351d7d928a6aea1524.
