### ISSUE TITLE
js_of_ocaml and missing runtime with base from opam

### ISSUE THREAD

**Issue by prepor** [janestreet/base#34]
Version: v0.9.4 (opam) OCaml 4.05 / 4.06

Hello. When I'm trying to compile something with base by js_of_ocaml, I have such errors:

```
Missing primitives:
  Base_am_testing
  Base_internalhash_fold_float
  Base_internalhash_fold_int
  Base_internalhash_fold_int64
  Base_internalhash_fold_string
  Base_internalhash_get_hash_value
```

As I understand, it's because META file doesn't contain
```jsoo_runtime = "runtime.js"```
so the compiler knows nothing about the implementation of these functions.

If I install base manually, META starts to contain this information and my compilation is successful.

**Comment by hhugo** [comment]
This should be solved in the upcoming release.

**Comment by hhugo** [comment]
v0.10 is out

**Comment by adrien-n** [comment]
I also see that with opam, ocaml 4.05.0, and base 0.11.0. The jsoo_runtime = "runtime.js" line is present. Code fails at runtime with "uncaught exception: 0,248,Failure,-3,Base_am_testing not implemented". I don't know if this issue is the same as the one upon which the @prepor has stumbled upon.

**Comment by adrien-n** [comment]
The build is inherited from ocsigen-start so it's not itself straightforward. I think the relevant bits are the following ones:

> js_of_eliom -w +A-4-7-9-37-38-39-41-42-44-45-48 -ppx -o local/var/www/prose/prose_tmp.js  -package base -package lwt.ppx -package js_of_ocaml.ppx -package js_of_ocaml-ppx.deriving -package ppx_deriving.std -package ocsigen-start.client -package ppx_deriving_yojson -package containers.data  _client/prose_db.cmo _client/prose_types.cmo _client/prose_i18n.cmo _client/prose_config.cmo _client/prose_container.cmo _client/prose_services.cmo _client/prose_formats.cmo _client/prose_language.cmo _client/prose_base.cmo _client/prose_handlers.cmo _client/prose_quill.cmo _client/prose_welcome.cmo _client/prose_page.cmo _client/prose.cmo

**Comment by hhugo** [comment]
you need to add `+base/runtime.js` to the command line invocation. see https://github.com/ocsigen/eliom/issues/554

**Comment by adrien-n** [comment]
Great, thanks! It works now. Sorry for asking on the wrong ticket. :)
