### ISSUE TITLE
v0.10.0 conflicts with merlin

### ISSUE THREAD

**Issue by kandu** [janestreet/base#35]
It's weird that after upgrading base from v0.9.4 to v0.10.0, merlin doesn't show types, complete for external PKGs which is listed in the .merlin file.
If base is installed explicitly by opam install base.v0.9.4, merlin just works well.

**Comment by kandu** [comment]
the problem occurs after opam upgrade.
ocaml 4.06
ocamlfind 1.7.3
base v0.10.0
merlin 3.05

**Comment by trefis** [comment]
I'm sorry but I cannot reproduce the problem.
I just created a fresh 4.06 switch, opam installed merlin and base and created a test directory with a `.merlin` containing the following line:
```
PKG base
```
then if create an arbitrary `.ml` file in that directory and try to complete on Base (and its submodules) everything works fine.

Could you tell me a bit more about your setup?
- what is the content of your .merlin
- how do you compile your project
- what's the output of:
  - `M-x merlin-version` (if you're using emacs) or `:MerlinVersion` (if you are using vim)
  - `M-x merlin-error-check` (if you're using emacs) or `:MerlinErrorCheck` (if you are using vim)

**Comment by kandu** [comment]
trefis, Thanks for your reply. After latest opam update & upgrade, the problem went away.
Since base.v0.10.0 and its related packages were published on the official opam repo yesterday, it could be that I do opam update in the "publishing" stage and cause a partial opam upgrading.
