### ISSUE TITLE
merlin-locate fails with Base and other Jane Street libs

### ISSUE THREAD

**Issue by yminsky** [janestreet/base#36]
I'm not 100% sure if this is an issue with the installation of Jane Street libraries, or a problem with Merlin, but Merlin-locate seems highly confused. If I write:

``` ocaml
open Base

let x = List.map
```

and then do a merlin-locate on the value List.map, I end up in the stdlib, not in Base. This is true for other JS libraries (e.g., Core, Async), but not other libraries like Cohttp. For things like Async, where there's no stdlib alternative, I get the "not in environment" error.

Note that Merlin does get types right in this context, and this is using jbuilder, so the .merlin file should be set up appropriately.

This is using the latest stable releases of everything on opam, which means the 0.10 version of Base, and merlin 3.0.5.

**Comment by hhugo** [comment]
I was able to reproduce this issue. I seems to work fine with merlin 3.0.4.
cc @let-def

**Comment by yminsky** [comment]
Yup. Rolling back to Merlin 3.0.4 fixed the issue. Maybe it's a bug there?

**Comment by hhugo** [comment]
fixed in dune
