### ISSUE TITLE
Dependency loop: base depends on sexplib depends on base

### ISSUE THREAD

**Issue by tautschnig** [janestreet/base#37]
I have no idea how either base or sexplib can be built as they mutually depend on each other.

**Comment by hhugo** [comment]
What make you think base depend on sexplib ? Base only depend on jbuilder, see https://github.com/janestreet/base/blob/master/base.opam#L12

**Comment by tautschnig** [comment]
Not quite true in the latest release: https://github.com/janestreet/base/blob/00f7aa62946663ebf87c5040b3881dd238d8c4b2/src/jbuild#L30

**Comment by tautschnig** [comment]
But then it seems the released version of sexplib does not have the dependency on base - I had wrongly looked at master for sexplib. Closing.
