### ISSUE TITLE
base does not currently compile under Windows

### ISSUE THREAD

**Issue by nojb** [janestreet/base#48]
Due to the use of some `gcc`-isms:

1. `exn_stubs.c`, uses `__attribute((unused))`
2. `int_math_stubs.c`, uses `__builtin_popcount`.

**Comment by diml** [comment]
I'm looking at this. For int_math_stubs, I'm using this code (hopping it works):

```c
#ifdef _MSC_VER

#include <intrin.h>

#define __builtin_popcountll __popcnt64
#define __builtin_popcount   __popcnt

static uint32_t __inline __builtin_clz(uint32_t x)
{
  int r = 0;
  _BitScanForward(&r, x);
  return r;
}

static uint64_t __inline __builtin_clzll(uint64_t x)
{
  int r = 0;
  _BitScanForward64(&r, x);
  return r;
}
#endif
```

**Comment by nojb** [comment]
Great, looks good & compile passes.

**Comment by XVilka** [comment]
Were any updates on this one?

**Comment by diml** [comment]
This has been pushed to github, thought it might not be in the opam repository yet

**Comment by seliopou** [comment]
I believe this has reached OPAM.
