### ISSUE TITLE
Incorrect docs in Map.find

### ISSUE THREAD

**Issue by pbiggar** [janestreet/base#54]
The [docs for `Map.find`](https://ocaml.janestreet.com/ocaml-core/v0.11/doc/base/Base/Map/#val-find) say:

> Returns the value bound to the given key, raising Caml.Not_found of Not_found_s if none exists.

However, the [docstring for `Map.find`](https://github.com/janestreet/base/blob/b82b7647fed3c8b5760c24d9237dd094c3c84824/src/map_intf.ml#L1491) says:

    (** Returns [Some value] bound to the given key, or [None] if none exists. *)

which matches what it looks like the code does, and the natural expression of `find`.

So it seems that the doc generator is pulling the [comment for `Map.find_exn`](https://github.com/janestreet/base/blob/b82b7647fed3c8b5760c24d9237dd094c3c84824/src/map_intf.ml#L1493) instead of `Map.find`.

**Comment by diml** [comment]
The docs link is for version v0.11 of base, while the docstring one is for master. The comment was fixed in master since the v0.11 release.
