### ISSUE TITLE
The Sequence module is missing fold_until in the documentation

### ISSUE THREAD

**Issue by rbjorklin** [janestreet/base#64]
The `Sequence.fold_until` function is missing from [this page](https://ocaml.janestreet.com/ocaml-core/latest/doc/base/Base/Sequence/). Also it would be really nice with a simple example of how to use this function.

**Comment by rbjorklin** [comment]
Ah, I hadn't noticed it was possible to expand some of the modules. That documentation was actually one of the most helpful I've found on there but a usage example would still be nice!

**Comment by bcc32** [comment]
The `fold_until` documentation now includes this example snippet.
