### ISSUE TITLE
Moving Arg and Doubly_linked from Core_kernel to Base?

### ISSUE THREAD

**Issue by TheAspiringHacker** [janestreet/base#68]
To my understanding, Base is the minimal JS-compatible standard library and Core_kernel is the more featureful one. I previously used Base for a project, but just switched to Core_kernel because I specifically needed the doubly linked list.

IMO a lot of the modules in Core_kernel aren't essential, but a doubly-linked list is generally something that a standard library should have. I think that Doubly_linked deserves to be in Base.

Also, I don't see why Arg needs to be in Core_kernel, because since it is in the original standard library, it shouldn't add any code size overhead.

**Comment by yminsky** [comment]
I think Arg is not included in Base because we think it's not a great
library. Command is used instead in the Core/Async world, and Cmdliner is
another worthy option.

Doubly_linked is plausible, but I think there are a lot of plausible
candidates there. Anyway, a question for the Base devs.

**Comment by seliopou** [comment]
Remember that Base is meant to be used everywhere, including JavaScript. In that environment `Arg` doesn't make much sense, so it's not included. Note however, if you want access to it, you can do:

```ocaml
open Base
module Arg = Caml.Arg
```

With respect to `Doubly_linked`, it has a bunch of dependencies (including a union find data structure, among others) that we're not keen on including in base. That may change in the future, but for now that's where we are.
