### ISSUE TITLE
Add Map.insert_with

### ISSUE THREAD

**Issue by copy** [janestreet/base#69]
This is a function from Haskell ([`insertWith`](https://hackage.haskell.org/package/containers-0.6.0.1/docs/Data-Map-Strict.html#v:insertWith)) with signature `'a t -> key:key -> data:'a -> f:('a -> 'a -> 'a) -> 'a t` that I often miss when programming in OCaml. For example, it's useful for implementing `incr` and similar functions: `Map.insert_with m ~key ~data:incr_count ~f:(+)`.

The closest function that base currently has is `update : 'a t -> key -> f:('a option -> 'a) -> 'a t`.

If accepted, I'll gladly contribute a pull request.

**Comment by yminsky** [comment]
Map.update and Map.change do indeed seem to be in the same neighborhood. My first instinct is to think that this doesn't provide enough unique value to be worth adding. A good way of arguing the other side would be to provide some examples of code that would be made cleaner and nicer with this function, as opposed to change or update.

**Comment by copy** [comment]
It's mostly a generalisation of `incr` (which exists in `Hashtbl` but not in `Map`) that let's you specify the combining operator. It's also than `update` because it only mentions the value-to-be-inserted once.

```diff
-      let amount = entry.amount in
-      M.update per_category ~key:c (function None -> amount | Some old -> old + amount)
+      M.update_with per_category ~key:c ~data:entry.amount ~f:(+)
```

I actually haven't found many use-cases besides `insert_with ~f:(+)` or `insert_with ~f:List.append`. Feel free to close if you think it doesn't provide enough unique value.

**Comment by yminsky** [comment]
Yeah, my tendency is to not think it's worth adding a special function to Map for this. 

FWIW, maybe another nice approach would be to define a function like:

``` ocaml
val z f x opt =
   match opt with
   | None -> x
   | Some x' -> f x' x
```

And then you could do:

```ocaml
M.update per_category ~key:c (z (+) x)
```

But one would need a better name than `z`. But with an appropriate name, I could imagine adding such a thing to Option.

**Comment by copy** [comment]
> But one would need a better name than z. But with an appropriate name, I could imagine adding such a thing to Option.

Interesting. Looks like `Option.fold`:

```ocaml
M.update per_category c (Option.fold ~init:entry.amount ~f:(+))
```
I think this works for me. Cheers!
