### ISSUE TITLE
Unable to install from opam

### ISSUE THREAD

**Issue by CT075** [janestreet/base#80]
Currently, when I run `opam install base` on a fresh switch with the most recent version of ocaml (4.08), I get this error:

![image](https://user-images.githubusercontent.com/7939129/66795653-42ef4d00-eed3-11e9-9ff7-13b3414212c1.png)

I first encountered this when attempting to upgrade base, but this happens even fresh.

I thought maybe there was an error with my environment, but I was unable to determine what might be causing a problem.

**Comment by bcc32** [comment]
This appears to be OCaml 4.09, judging from the log.  I think we might not be 4.09-compatible yet.

**Comment by CT075** [comment]
Oops, you're right; it looks like my system upgraded ocaml without me noticing.

Thanks for the info!
