### ISSUE TITLE
Build through opam fails - Unbound module Cmo_format

### ISSUE THREAD

**Issue by tigerjack** [janestreet/base#82]
As the title says, I got the following error when installing base through opam.

> ocamlc compiler-stdlib/gen/.gen.eobjs/byte/gen.{cmi,cmo,cmt} (exit 2)
> (cd _build/default && /usr/bin/ocamlc.opt -w -40 -g -bin-annot -I compiler-stdlib/gen/.gen.eobjs/byte -I /usr/lib/ocaml/compiler-libs -no-alias-deps -o compiler-stdlib/gen/.gen.eobjs/byte/gen.cmo -c -impl compiler-stdlib/gen/gen.ml)
> File "compiler-stdlib/gen/gen.ml", line 59, characters 33-51:
> 59 |      let toc = (input_value ic : Cmo_format.library) in
>                                        ^^^^^^^^^^^^^^^^^^
> Error: Unbound module Cmo_format

Do you know how to fix it? Thanks in advance.

**Comment by hhugo** [comment]
Which version are you trying to build ?

**Comment by tigerjack** [comment]
I was trying to build the default version provided by opam (I think), that is v0.12.2.
For the compiler part, I'm using version 4.09.0-1 provided by Archlinux.

**Comment by hhugo** [comment]
There seems to be an issue with your ocaml installation
The file `cmo_format.cmi` seem to be missing from `/usr/lib/ocaml/compiler-libs/`

**Comment by tigerjack** [comment]
@hhugo you're right, I have no such file. Is there any way I can install it? I have found no solution up to now.

**Comment by hhugo** [comment]
Try installing ocaml-compiler-libs https://www.archlinux.org/packages/extra/x86_64/ocaml-compiler-libs/

**Comment by tigerjack** [comment]
Sorry, maybe I wasn't so clear. I already installed that package from the official Arch repository. The problem is that it doesn't contain the `cmo_format.cmi` file, as you can see [here](https://www.archlinux.org/packages/extra/x86_64/ocaml-compiler-libs/files/). Is it possible that this file was added recently and it is still not added to the Arch package? Do you know any other way to get the compiler libs?

**Comment by hhugo** [comment]
That file was always part of the ocaml compiler distribution. I believe the arch package is broken.
`cmo_format` use to be located under the `bytecomp/` directory but starting with ocaml 4.09, it was moved under the `file_formats/` directory.
Please report the issue to the maintainer of the arch package.
