### ISSUE TITLE
base is currently broken on the 4.10 release branch

### ISSUE THREAD

**Issue by gasche** [janestreet/base#83]
This is a tracking issue for the fact that `base` is currently broken on the 4.10 release branch, which will shortly turn into a 4.10 beta, and eventually into a 4.10 release. Having base unavailable on 4.10 would prevent all its users from adopting the new release.

One compatibility issue with `base` was reported by @stedolan in https://github.com/ocaml/ocaml/issues/9014#issuecomment-553455493 : it uses C stubs to implement a function to clear the current backtrace, but the C stub uses an internal/unexported runtime variable and it is broken by an upstream change to move global runtime state into a record (for Multicore preparation).

**Comment by tcoopman** [comment]
Is there any progress being made on this issue?

**Comment by gasche** [comment]
Apparently there was some compatibility work, see #85 which made its way into the [v0.13.1 release](https://github.com/janestreet/base/releases/tag/v0.13.1) last February. Can't you find base 0.13.1 in opam?

**Comment by tcoopman** [comment]
Indeed, must have looked over that because of this open issue? I guess this issue can be closed then?
