### ISSUE TITLE
Rule running discover.exe is wrong in cross-compilation setups

### ISSUE THREAD

**Issue by jeremiedimino** [janestreet/base#88]
Because it depends on the target discover.exe binary for no reason.

I fixed the issue by removing the `(deps ...)` field internally, and I'm opening this issue to remind myself to do a minor release once the change surfaces back on github.

**Comment by xclerc** [comment]
Fixed by https://github.com/janestreet/base/commit/50f3b3e7363b6709601c23087f71dd0567b59869.
