### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by dorafmon** [janestreet/base#9]
Hi, I am trying to see how to set up jbuilder for my own project to build tests. How do you run tests in base? I see a jbuild file in the test folder but `jbuilder base_test` does not work for me. Thanks!

**Comment by diml** [comment]
Running tests is not fully setup in jbuilder. You can define your own tests this way:

```ocaml
(alias
  ((name runtest)
   (deps (test_runner.ml))
   (action "./test_runner.exe")))
```

But there is still something missing to run them. It is planned to add `jbuilder runtest` for this purpose.

For the special case of inline test (`let%test _ = true`), it is also planned to add automatic support. i.e. `jbuilder runtest` will automatically build a test runner and run the tests.

**Comment by dorafmon** [comment]
But in this particular case, how do you run tests for `base`? Thanks!

**Comment by diml** [comment]
When inline tests are setup in jbuilder, you'll be able to do `jbuilder runtest` in Base to run the tests

**Comment by dorafmon** [comment]
Hi thanks!

**Comment by 0xc0** [comment]
Has the ability to run tests been added in jbuilder? If not, what can I do to run all of the tests in base?

I would like to hack on base, but not being able to run the suite of tests is going to slow me (and others outside of Jane Street) down.

**Comment by rgrinberg** [comment]
@0xc0 there's WIP to get this working here: https://github.com/janestreet/jbuilder/pull/338

Hopefully soon.

**Comment by brendanlong** [comment]
This is supported in Dune now, but I still can't figure out how to run the tests. `dune runtest` doesn't do anything, and if I add `(inline_tests)` to test/jbuild, I get weird errors involving dependencies (two versions of `base`). I'm guessing the issue is that ppx_inline_test depends on base, so I need to do some sort of complicated dance to get them to work together. Is there a script or something that Jane Street uses to run these?

**Comment by diml** [comment]
Could you try adding `(allow_overlapping_dependencies true)` for the tests? That might help.

The general issue with tests in JS packages is that they are only tested inside our internal mono-repository. It might be possible to set them up properly in the github repositories, however it is not clear how much work this represents. We could probably make an exception for Base though.
