### ISSUE TITLE
Inconsistent exceptions between Array & List modules

### ISSUE THREAD

**Issue by ytrellu** [janestreet/base#90]
Applying Array.map2_exn [1] onto arrays of differing lengths will throw a generic invalid_arg exception, unlike List.map2_exn which throws a well formatted check_length2_exn exception.

And again just like for List, the Or_unequal_lengths module could also be used to add Array.map2.

Happy to create a PR to solve these.

[1] https://github.com/janestreet/base/blob/2a1217c6fe3ae3a7b1a5ff03e8ac6b0ea4e17333/src/array.ml#L471

**Comment by bcc32** [comment]
Hi @ytrellu, that's a good point!  We could certainly improve the message raised by `Array.map2_exn` in this case, for example by including the actual lengths of the arguments.  A PR would definitely be welcome, if you would like to submit one :)

I don't think there's as much to be gained from using the `Or_unequal_lengths` module in `Array`, though.  Most of the reason for having that variant returned by `List.map2_exn` is that it's hard/slow to check beforehand whether the operation might fail (well, it takes linear time).  Meanwhile, arrays are created with a fixed length and it is easy and fast to check whether they have the same length, so just having the `_exn` raising versions seems more okay.

**Comment by ytrellu** [comment]
Hi @bcc32, the relationship between the cost of checks and the use of error aware return types is new to me, definitely food for thought!

So I started taking a look but I already fail at the first step, which is to have `test_array.ml` running. I tried to build using what is in the makefile, without success:

```
opam@e167c95bcf8b:~/ws/base$ dune external-lib-deps --missing @install
opam@e167c95bcf8b:~/ws/base$ dune build
File "src/import.ml", line 3, characters 8-40:
3 | include Sexp.Private.Raw_grammar.Builtin
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module Sexp.Private.Raw_grammar
opam@e167c95bcf8b:~/ws/base$ cat /etc/os-release | head -n 1
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
opam@e167c95bcf8b:~/ws/base$ opam switch | tail -n 1
→  4.10    ocaml-base-compiler.4.10.0  4.10
opam@e167c95bcf8b:~/ws/base$ opam install sexplib0 sexp
[NOTE] Package sexp is already installed (current version is v0.13.0).
[NOTE] Package sexplib0 is already installed (current version is v0.13.0).
```

I'll take a look later when I have time, but of course pointers would help me here : ).

**Comment by bcc32** [comment]
I think this is a mismatch between the version of `base` and `sexplib0`.  You'll need the `sexplib0` master branch from GitHub, I suspect, to compile the corresponding version of Base.  (Looks like you're using the opam docker images, so here's what I used:)

```
FROM ocaml/opam2
RUN opam install -y dune dune-configurator
RUN mkdir $HOME/ws
WORKDIR $HOME/ws
COPY dune-project .
RUN git clone https://github.com/janestreet/sexplib0
RUN git clone https://github.com/janestreet/base
WORKDIR base
```

Running `dune build` in this image succeeds for me.  `dune-project` is just a dummy file containing:

```
(lang dune 2.0)
```

(You can also just clone `sexplib0` into `base/vendor` or some other directory, but that is harder to scale up to multiple levels of dependencies).

**Comment by ytrellu** [comment]
Thanks for that image, I could reproduce it as well. In the end I stopped trying to have the tests run, as I could not find any up-to-date walk through. I just copied the parts of the file with the modifications and made sure it was compiling.
